### PR TITLE
Get rid of slices for optional elements in bundle

### PR DESCRIPTION
**Pull request by markkramerus**
Keep conformance expectations in narrative.

### CODE REVIEW

**Comment by markkramerus** [comment]
After much consideration, I came to the conclusion there is no better option than what Saul calls "Option 0".

**Review by mlterryMitre — APPROVED** [review]
The changes unfortunately dilute interoperability but I understand why this was done.

**Review by saulakravitz — APPROVED** [review]
Looks good.
I still like having an abstract CancerCondition profile, but that would be more work to update everything, so I'm fine with leaving it with this simplification of the status quo.

**Review by saulakravitz — APPROVED** [review]
I think you need to change a MUST to a SHOULD in http://build.fhir.org/ig/HL7/fhir-mCODE-ig/branches/keeping-it-simple/StructureDefinition-mcode-patient-bundle.html#usage.

The bundle MUST==>SHOULD.also contain following mCODE-conformant resources, if available to the server:

**Review by masnick — APPROVED** [review]

**Pull request merged**
