### PR TITLE
Add macOS script wrappers

### PR DESCRIPTION
**Pull request by masnick**
Adds script wrappers for macOS users. See `script/README.md` for details.

Screenshot of the build completion notification you get with `script/build`:

E1C5405A-EA63-4335-ABB1-9FF76C108848

Screenshot of the QA errors display you get with `script/build`:

Screen Shot 2020-11-24 at 3 07 31 PM

### CODE REVIEW

**Comment by masnick** [comment]
Per @mlterryMitre's request, you now need to set `SHOW_ERRORS_AFTER_IG_BUILD=1` to show QA errors after the build.

**Review by markkramerus — COMMENTED** [review]
I like the general idea. Two comments:
1) Do you forseee having to change this if _genonce changes? Or do you think those changes are well-encapsulated?
2) You need to nominate someone from the FSH team to review the code, I can't.

**Comment by masnick** [comment]
@markkramerus:
 
> 1. Do you forsee having to change this if _genonce changes? Or do you think those changes are well-encapsulated?

Yes, it should work fine if _genonce changes — as long as _genonce still builds the IG and continues to follow the shell convention of `exit 0` on successful completion, the wrapper will work.

> 2. You need to nominate someone from the FSH team to review the code, I can't.

Ok, I’ll do this after @mlterryMitre has a chance to look at it.

**Comment by masnick** [comment]
Moved out of the IG into a separate repo.

**Pull request closed without merging**
