### PR TITLE
Add value sets to data dictionary diff, update data dictionary and diff with the v1.8.5 content

### PR DESCRIPTION
**Pull request by masnick**
# Data dictionary diff

This PR updates the diff to use v1.8.5 content (previous version was v1.8.0), in addition to the following changes:

- Value set diff capability was added
- Version numbers (pulled from sushi-config.yaml) were added to the first tab
- Remapping added to reflect rename from TNM Stage Group to Cancer Stage Group

# Data dictionary

This PR updates the data dictionary to use v1.8.5 content (previous version was v1.8.0).

There are no changes to the data dictionary generation code, but content has changed due to updates to the IG, including:

```
Profile rename:
  Old: http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-tnm-stage-group 
  New: http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-cancer-stage-group 


3 changed element(s)
Default > Brachytherapy Treatment Phase Extension > Technique
http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-brachytherapy-treatment-phase>http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-brachytherapy-treatment-phase>Procedure.extension:technique
┌───────────────────┬────────────┬──────────┐
│ Field             │ Old        │ New      │
├───────────────────┼────────────┼──────────┤
│ Value Set Binding │ extensible │ required │
└───────────────────┴────────────┴──────────┘

Default > Genomic Region Studied Value
http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-genomic-region-studied>http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-genomic-region-studied>Observation.value[x]
┌────────────┬──────────────────────────┬──────────────────────────────┐
│ Field      │ Old                      │ New                          │
├────────────┼──────────────────────────┼──────────────────────────────┤
│ Definition │ The Laboratory result... │ Not used in this profile.... │
└────────────┴──────────────────────────┴──────────────────────────────┘

Default > Primary Cancer Condition Stage > Assessment
http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-primary-cancer-condition>http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-primary-cancer-condition>Condition.stage.assessment
┌───────────┬──────────────────────────────┬─────────────────────────────┐
│ Field     │ Old                          │ New                         │
├───────────┼──────────────────────────────┼─────────────────────────────┤
│ Data Type │ Reference: TNMStageGroup,... │ Reference: CancerStageGroup │
└───────────┴──────────────────────────────┴─────────────────────────────┘
```

# Other changes

I reorganized the downloads page to put the links in the relevant sections. I found the list of all downloads at the bottom difficult to visually parse.

# Code review

Please consider the following:

1. Does the contents of the new value set and value set code tabs make sense? I have not done a manual review since as far as I know there's not an efficient way to do this (there's no equivalent to putting the IG publisher snapshots side by side for any but the shortest of value sets). So it would be helpful if you can do a "sniff test" review as a first pass at validating the value set-related output of the tool.
2. Do we want the "Value set - changed codes" tab at all? This mirrors the approach for the profile elements, but for the value sets it only shows changes in the code description since all the other fields are used as the key for the code.

### CODE REVIEW

**Comment by masnick** [comment]
Updates include:

- Remove `.` from ICD codes when diffing. The codes now appear as changed rather than added/removed. Still not sure if it's worth keeping the "changed codes" tab in the diff.
- Added .json version of the data dictionary into the git repo (not part of the CI build though). This will facilitate a command that will show "changes since last commit" or "changes since last release" in the terminal.
- Updated .gitignore to exclude Excel temp files

**Comment by markkramerus** [comment]
In the yaml file, you say: ""the US Core Laboratory Result Observation Profile for Complete Blood Count (CBC), and Comprehensive Metabolic Panel (CMP)".  Actually, there are no specific profiles for CBC and CMP in US Core. It was just felt it wasn't mCODE's place to define them.

**Review by markkramerus — CHANGES_REQUESTED** [review]
#4 in my comments is the big thing.
#1 should be fixed, but it is minor.

**Comment by markkramerus** [comment]
Another thing I realized -- the + and - buttons that appear on the value set tab. The way they are presented in Excel is terrible. They are unworkable and confusing. In theory they would be highly desirable, but in practice, they suck.
I vote to remove them. Max? May? Do you agree?

**Comment by masnick** [comment]
Updated with a new version of the dd and ddd.

For @markkramerus's comments above:

> 1. In the yaml file, you say: ""the US Core Laboratory Result Observation Profile for Complete Blood Count (CBC), and Comprehensive Metabolic Panel (CMP)".  Actually, there are no specific profiles for CBC and CMP in US Core. It was just felt it wasn't mCODE's place to define them.

I simplified this:

```markdown
**Profiles not shown in data dictionary:** Profiles that are used by mCODE but defined externally to mCODE,
such as vital signs (defined by FHIR or US Core), are not included in the Data Dictionary.
```

> 2. I like the "Value Sets - changed codes" tab. We might be wasting electrons, but I would recommend keeping it as-is.

Ok, sounds good.

> 4.  In Value Set Codes tab, the lists of values repeat. For example, there are only 8 codes in **Elixhauser Comorbid Condition Value Set for HIV-AIDS** but the table shows 24 -- each code is repeated 3 times. I think this is happening throughout. Yep, everything is triplicate.

I still have no idea what happened here. When I re-ran the generation script it produced the value sets without duplicates. As soon as the data dictionary generation code gets into a package manager, I will add the script version into the metadata for the data dictionary so it's possible to trace bugs like this. In any case, it's fixed now.

> Another thing I realized -- the + and - buttons that appear on the value set tab. The way they are presented in Excel is terrible. They are unworkable and confusing. In theory they would be highly desirable, but in practice, they suck.
I vote to remove them. Max? May? Do you agree?

I completely agree that the way Excel implemented expand/collapse feels like a giant off by one error, and should not be collapsed by default.

I do think there is some value in leaving them in _expanded_ by default.

1. They are a useful visual indicator of when a value set ends and the next begins (as long as you don't try clicking on them).
2. They add some, ahem, highly discoverable buttons that are useful (at least for me; I prefer this to the filter dropdown in the header, for example): clicking on "2" collapses all value sets and "3" expands all of them.  Napkin 03-08-21, 7 36 06 AM

If you think expanded by default will still be confusing to users, I can take it out entirely. But my guess is the vast majority of people won't even notice.

**Pull request merged**
