### PR TITLE
Oncology specimen -- responding to https://jira.hl7.org/browse/FHIR-41051

### PR DESCRIPTION
**Pull request by saulakravitz**
HumanSpecimen --> OncologySpecimen.
Reworked specimen type valueset to use http://terminology.hl7.org/CodeSystem/v3-SpecimenType.

Responding to https://jira.hl7.org/browse/FHIR-41051

### CODE REVIEW

**Comment by saulakravitz** [comment]
Sigh... https://terminology.hl7.org/CodeSystem-v3-SpecimenType.html doesn't include TUMOR ....so the choice might need a rethink

**Comment by mlterryMitre1** [comment]
Re:  _https://terminology.hl7.org/CodeSystem-v3-SpecimenType.html doesn't include TUMOR....so the choice might need a rethink._ 
Agreed. Guessing it was revised by the vocabulary group because a tumor is not a specimen by definition. It is an abnormal state found in a specimen. So the specimen type would be tissue or blood or other.

**Review by mlterryMitre1 — CHANGES_REQUESTED** [review]
We don't want to limit genomics specimens to only oncology specimens (i.e. tumors). That assumes that we only support somatic variants. Genomic tests could use normal specimens for cancer screening or as part of a normal tissue for use in tumor-normal tests.

**Comment by saulakravitz** [comment]
Current proposal is to use https://terminology.hl7.org/5.1.0/CodeSystem-v2-0487.html instead.  Much broader (for good and for ill).

**Review by markkramerus — COMMENTED** [review]
We've gone full circle on this and arrived at a point where the original HumanSpecimen and the associated value set is better than the proposed change to OncologySpecimen. Not only is the value set more focused, the name is better (see May's comment about not limiting the type of specimen to "oncology".  Disapproving and closing.

**Comment by markkramerus** [comment]
See comment above.

**Pull request closed without merging**
