### PR TITLE
Add custom grouping for artifacts

### PR DESCRIPTION
**Pull request by masnick**
This PR adds custom groupings on the `artifacts.html` page: rather than all the profiles appearing together in the same section, this PR splits them into separate sections following the [conceptual model](http://hl7.org/fhir/us/mcode/mCodeDiagram.png).

Extended Example 1 resources are also given their own section, separate from the other examples.

Experimental profiles and their examples are in their own sections.

You can see [how the new organization looks here](https://build.fhir.org/ig/HL7/fhir-mCODE-ig/branches/artifact-custom-grouping/artifacts.html) (vs. [old](http://hl7.org/fhir/us/mcode/artifacts.html)).

I also added in the `CancerRelatedMedicationRequest` profile to `experimental.md`, which is semi-unrelated but needed to be done.

Note: There is a nonfatal build issue that I need to resolve before merging, which I believe is related to how SUSHI creates the artifact groups from `sushi-config.yaml`. This is the source of the `id value '$something' is not valid` errors in `qa.html`.

### CODE REVIEW

**Review by markkramerus — CHANGES_REQUESTED** [review]
Max, this is MUCH nicer. My only suggestion is to optimize the order of items on the page. I suggest the following:

- Profiles (using the six areas in the same order as on the index page)
- Extensions
- Value Sets
- Examples
- Experimental

Lastly, can you come up with a better name than "Extended example 1"?

**Comment by masnick** [comment]
I've re-organized as Mark suggested, but we're bit by a SUSHI bug again, which I have attempted to fix here: https://github.com/FHIR/sushi/pull/646

The issue is that SUSHI doesn't support separate `id` and `name` values for custom groups. Right now it uses `name` for `id`, which causes errors in `qa.html`. **You can still build the IG with the current SUSHI beta**, it will just have >100 errors related to this in `qa.html`.

---

Possible names for "Extended example 1" -- I'm assuming we may have more "extended examples" in the future.

- (Current) Extended example 1
- Example: Patient M
- Example: Breast Cancer Patient 
- Comprehensive Example 1
- Comprehensive Example 1: Patient M
- Comprehensive Example 1: Breast Cancer Patient
- mCODE Patient Bundle Example 1
- mCODE Patient Bundle Example 1: Breast Cancer Patient

Note that I've named the mCODE bundle `mCODE Patient Bundle` to distinguish from other bundles we might have. So I wouldn't want to use "mCODE Bundle" without the "Patient" unless we decide to change this.

The current pattern for the "extended example" resource ids is `$prefix-$profile_name` (e.g., `example1-mcode-cancer-patient`). I'm happy to change this if we can come up with a better pattern, but we can certainly change the `$prefix` as well as the prose name of the "extended example". Possible options:

- (Current) `example1`
- `ex1`
- `bundle-ex1`
- `patientm`

My favorite of these are:

- Comprehensive Example 1: Breast Cancer Patient _(I know it is long, but I prefer descriptive over brevity for this.)_
- Use `ex1` for the prefix for resource names, so we would get `ex1-mcode-cancer-patient`, etc.

Please let me know what you think about the naming. Thanks!

**Comment by markkramerus** [comment]
In terms of naming, we have the regular examples, named "Example01" "Example02" etc.  These could be changed globally to "Example1" and "Example2". The "0" serves no purpose. 
Then, you could do "Scenario1" or "Example3" or "Story1"

**Comment by masnick** [comment]
> In terms of naming, we have the regular examples, named "Example01" "Example02" etc. These could be changed globally to "Example1" and "Example2". The "0" serves no purpose.
> Then, you could do "Scenario1" or "Example3" or "Story1"

I like naming the stand-alone example instances like `Example1` and then naming all the related examples `Scenario1`.

This would give us **Scenario 1: Breast Cancer Patient** to replace "Extended Example 1", which I like as well.

I'll make these changes and submit for final review before merging. Thanks!

**Comment by masnick** [comment]
@markkramerus this PR is updated to address the following:

- Rename "extended example 1" to "scenario 1"
- Rename the other examples from "example01" to "example1"
- Update the artifact groups to reflect the changes to `master`
- Rename the tumor size example resources to have `example` in their path

The QA page is clean locally, with the exception of a few pre-existing errors and the errors caused by the [SUSHI issue](https://github.com/FHIR/sushi/pull/646).

**Review by markkramerus — APPROVED** [review]

**Pull request merged**
